---
version: 3.0.0
slug: custom_git_pull
name: Custom Git Pull
description: Custom git pull to update the local configuration
url: https://github.com/dylanl321/ha-addons/tree/main/custom_git_pull
arch:
  - aarch64
  - amd64
boot: manual
hassio_api: true
hassio_role: homeassistant
image: ghcr.io/dylanl321/{arch}-addon-custom_git_pull
init: false
map:
  - config:rw
options:
  repository: null
  git_branch: main
  git_remote: origin
  auto_restart: false
  restart_ignore:
    - ui-lovelace.yaml
    - .gitignore
  git_command: pull
  git_prune: false
  deploy_delete: false
  deploy_dry_run: false
  mirror_protect_user_dirs: true
  allow_legacy_config_git_dir: false
  deployment_key: []
  deployment_user: ""
  deployment_password: ""
  deployment_key_protocol: rsa
  repeat:
    active: false
    interval: 300
schema:
  repository: str
  git_branch: str
  git_remote: str
  auto_restart: bool
  restart_ignore:
    - str
  git_command: list(pull|reset)
  git_prune: bool
  deploy_delete: bool
  deploy_dry_run: bool
  mirror_protect_user_dirs: bool
  allow_legacy_config_git_dir: bool
  deployment_key:
    - str
  deployment_user: str
  deployment_password: password
  deployment_key_protocol: match(rsa|dsa|ecdsa|ed25519|rsa)
  repeat:
    active: bool
    interval: int
startup: services
